version: 2.1
jobs:
  #  CHECKOUT REPOSITORY
  checkout_repo:
    #    machine: true
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/iom-frontend
    steps:
      - checkout
      - attach_workspace:
          at: ~/iom-frontend
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .

  #  CHECKOUT FOR VULNERABILITIES IN LIBRARIES
  check_vulnerabilities:
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/iom-frontend
    steps:
      - attach_workspace:
          at: ~/iom-frontend
      - run: yarn validate:dependencies

  #  BUILD SOURCE AND DEPLOY TO SERVER
  build_deploy:
    #    machine: true
    docker:
      - image: circleci/node:10.13.0
    working_directory: ~/iom-frontend
    steps:
      - checkout
      - attach_workspace:
          at: ~/iom-frontend
      - run: yarn build
      - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          name: Add SSH KEY
          fingerprints:
            - "69:70:5c:6f:c0:c3:40:45:44:4a:f5:f7:ef:0f:8d:43"
      - run: eval ssh-agent -s
      - run: sudo sh -c 'echo "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list'
      - run: sudo apt-get update
      - run: sudo sh -c 'echo "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list'
      - run: sudo apt install rsync
      - run: rsync -ave  ssh ~/iom-frontend/build $SSH_USER@$SSH_HOST:~/projects/iom-frontend/

  #  EVALUATE BROWSER PERFORMANCE WITH LIGHTHOUSE
  test_performance:
    docker:
      - image: circleci/node:10.13.0-browsers
    working_directory: ~/iom-frontend
    steps:
      - attach_workspace:
          at: ~/iom-frontend
      - run: CI=true yarn lighthouse

  test_e2e:
    docker:
      - image: cypress/browsers:chrome67
    working_directory: ~/iom-frontend
    steps:
      - attach_workspace:
          at: ~/iom-frontend
      - run: yarn add cypress
      - run:
          command: yarn start
          background: true
      - run: yarn cy:record

# WORKFLOWS
workflows:
  version: 2
  test_build_deploy:
    jobs:
      - checkout_repo
      # - build_deploy:
      #     requires:
      #       - checkout_repo
      - test_performance:
          requires:
            - checkout_repo
      # - test_e2e:
      #     requires:
      #       - build_deploy
