version: 2
jobs:

  #  CHECKOUT REPOSITORY
  checkout_repo:
    #    machine: true
    docker:
    - image: circleci/node:9.11.1
    working_directory: ~/iom-frontend
    steps:
    - checkout
    - attach_workspace:
        at: ~/iom-frontend
    - restore_cache:
        keys:
        - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-cache-{{ .Branch }}
        - yarn-cache-
    - run: yarn install
    - save_cache:
        key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths: node_modules
    - persist_to_workspace:
        root: .
        paths: .

  #  CHECKOUT FOR VULNERABILITIES IN LIBRARIES
  check_vulnerabilities:
    docker:
    - image: circleci/node:9.0.0
    working_directory: ~/iom-frontend
    steps:
    - attach_workspace:
        at: ~/iom-frontend
    - run: yarn validate:dependencies

  #  BUILD SOURCE AND DEPLOY TO SERVER
  build_&_deploy:
    #    machine: true
    docker:
    - image: circleci/node:9.0.0
    working_directory: ~/iom-frontend
    steps:
    - checkout
    - attach_workspace:
        at: ~/iom-frontend
    - run: yarn build
    - run: sudo apt install rsync
    - run: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - add_ssh_keys:
        name: Add SSH KEY
        fingerprints:
        - "96:b4:44:5a:7c:d8:e4:3a:89:e1:79:ca:a6:42:79:78"
    - run: eval ssh-agent -s
    - run: rsync -ave  ssh ~/iom-frontend/build $SSH_USER@$SSH_HOST:~/iom-frontend-test/build

  #  EVALUATE BROWSER PERFORMANCE WITH LIGHTHOUSE
  test_performance:
    docker:
    - image: circleci/node:node:9.0.0-browsers
    working_directory: ~/iom-frontend
    steps:
    - attach_workspace:
        at: ~/iom-frontend
    - run: CI=true yarn lighthouse

  test_e2e:
    docker:
    - image: cypress/browsers:chrome67
    working_directory: ~/iom-frontend
    steps:
    - attach_workspace:
        at: ~/iom-frontend
    - run: yarn add cypress
    - run: yarn cy:record

# WORKFLOWS
workflows:
  version: 2
  test_build_deploy:
    jobs:
    - checkout_repo
    - build_&_deploy:
        requires:
        - checkout_repo
    - test_performance:
        requires:
        - build_&_deploy
    - test_e2e:
        requires:
        - build_&_deploy
